version: '3.7'

x-common: &common
  volumes:
    - "${PWD}:/opt/php-version-audit"
  working_dir: /opt/php-version-audit

services:
  composer:
    <<: *common
    image: composer:1.9

  php:
    <<: *common
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev

  phpstan:
    <<: *common
    image: phpstan/phpstan:0.12
    command: analyse ./src

  build:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.alpine
    image: lightswitch05/php-version-audit
