name: Auto Updates

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        ref: master
        fetch-depth: 10

    - name: Ensure latest commit with tags
      run: git fetch; git fetch --tags; git checkout master; git pull

#    - name: Get composer cache directory
#      id: composer-cache
#      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
#
#    - name: Cache composer dependencies
#      uses: actions/cache@v1
#      with:
#        path: ${{ steps.composer-cache.outputs.dir }}
#        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
#        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Run Update
      run: ./php-version-audit --full-update

    - name: commit updates
      run: ./github-commit-auto-updates.sh
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
